### ISSUE TITLE
GA4 Migration: Add GA4 Open Email Tracking Event

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-utils#153]
## User Story - Business Need
We are transitioning from UA to GA4 (Google Analytics 4).

Add a new `if` block in the jinja template for emails to include a new `ga4_open_email_url` image tag and setup the `HTMLEmailTemplate` to accept and use the new json object. The existing `ga_pixel_url` stuff should remain as-is for now.

- [ ]  Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As** VA Notify
**I want** to use the current version of GA
**So that** we are compliant with VA expectations

### Additional Info and Resources

- [Implementation and Ticket Overview](https://docs.google.com/presentation/d/1BKOQQyxlUsE08Z7mKhzWmUZmnsxKKU_NVCHJiUEgY58/edit?usp=sharing)

Template class:
<img width="612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d42d3d447b06806aa4c0907664b3995d9b82baed/image.png" alt="image.png" />

render call:
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5540169d8d4812849f627fe71824d2944363ca9d/image.png" alt="image.png" />

jinja template section that should be replicated and use `ga4_open_email_url` instead:
<img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e04de6318ad9757d70c5e85a565a6674dafb261d/image.png" alt="image.png" />

All code where ga_pixel_url is used:
<img width="614" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5777cbe784e32229076d3368fa6f90c17a3534fb/image.png" alt="image.png" />

- Existing GA3 pixel will be removed in a later ticket after the API work to remove the GA3 code is complete so we do not break the existing code

## Acceptance Criteria

- [x]  Existing `ga_pixel_url` functionality is untouched
- [x]  `HTMLEmailTemplate` class accepts an optional `ga4_open_email_url` and passes it to the `__str__` render call
- [x]  Add unit test to jinja template to ensure image tag is there

## QA Considerations

- The actual QAing of the image tag appearing in an email will take place on the corresponding API ticket linked in dependencies 1847

## Potential Dependencies
- There will be separate API tickets to send this code snippet with the email and to test the open tracking functionality

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/153?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/153?planning-poker) with Zenhub @cris-oddball

**Comment by MackHalliday** [comment]
@k-macmillan and @mjones-oddball - this ticket may need to be reviewed. 

We cannot do pixel tracking with GA4 - therefore, we need to create a POST request in the email template itself that will send a request to GA4 when opened.

**Comment by mjones-oddball** [comment]
Added stretch goal into the sprint for GA4 email open work.

**Comment by MackHalliday** [comment]
Friday 
- Update `notification-utils` with html for pixel tracking 
- Start on unit testing 

Today 
- Update `notification-api` test on DEV

**Comment by MackHalliday** [comment]
Moving into next Sprint. Issues testing locally, but able to test with unit tests. 
 
Pull request ready 
https://github.com/department-of-veterans-affairs/notification-utils/pull/157

**Comment by mjones-oddball** [comment]
This stretch goal was added into the sprint and started last Friday. Given Mack's latest update it will not be completed by the sprint end (today) as it needs more time for testing and PR review/approval.
